// Core session management

export type { TuiMode } from "@fleetagent/pi-tui";
// Config paths
export { getAgentDir, VERSION } from "./config.ts";
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type AgentSessionReloadResult,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
	type StructuredResponse,
	type StructuredResponseOptions,
} from "./core/agent-session.ts";
// Auth and model registry
export {
	type ApiKeyCredential,
	type AuthCredential,
	type AuthStatus,
	AuthStorage,
	type AuthStorageBackend,
	FileAuthStorageBackend,
	InMemoryAuthStorageBackend,
	type OAuthCredential,
} from "./core/auth-storage.ts";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.ts";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.ts";
// Extension system
export type {
	AgentEndEvent,
	AgentSettledEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	AutocompleteProviderFactory,
	BashResult,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderHeadersEvent,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	BuildSystemPromptOptions,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionToolBackendExecOptions,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MarkdownTransformContext,
	MarkdownTransformer,
	MessageRenderer,
	MessageRenderOptions,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionInfoChangedEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	SubagentToolCallEvent,
	TerminalInputHandler,
	ToolCallEvent,
	ToolCallEventResult,
	ToolDefinition,
	ToolExecutionMode,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WebsearchToolCallEvent,
	WebsearchToolResultEvent,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WriteToolCallEvent,
} from "./core/extensions/index.ts";
export {
	createExtensionRuntime,
	defineTool,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isSubagentToolResult,
	isToolCallEventType,
	isWebsearchToolResult,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "./core/extensions/index.ts";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.ts";
export {
	formatInstructionResourcesForPrompt,
	type InstructionResource,
	type InstructionResourceFrontmatter,
	InstructionResourceLoader,
	type InstructionResourceLoaderConfig,
	type InstructionResourceLoaderOptions,
	type InstructionResourceLoaderWithOperationsOptions,
} from "./core/instruction-resource-loader.ts";
export * from "./core/lsp/index.ts";
export { convertToLlm } from "./core/messages.ts";
export { ModelRegistry } from "./core/model-registry.ts";
export type {
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.ts";
export { DefaultPackageManager } from "./core/package-manager.ts";
export {
	type CreatePiAgentOptions,
	PiAgent,
	type PiAgentDiagnostic,
	type PiAgentRuntimeHost,
	type PiAgentServices,
	type PiAgentSessionOptions,
	type ResolvePiAgentSessionOptionsContext,
	type ResolvePiAgentSessionOptionsResult,
} from "./core/pi-agent.ts";
export type { PromptTemplate } from "./core/prompt-templates.ts";
export type {
	ProjectContextFile,
	ResourceCollision,
	ResourceDiagnostic,
	ResourceLoader,
} from "./core/resource-loader.ts";
export { DefaultResourceLoader, loadProjectContextFiles } from "./core/resource-loader.ts";
// Rules
export {
	formatRulesForPrompt,
	type LoadRulesFromDirOptions,
	type LoadRulesOptions,
	type LoadRulesResult,
	type LoadRulesWithOperationsOptions,
	loadRules,
	loadRulesFromDir,
	type Rule,
	type RuleFrontmatter,
	RuleLoader,
} from "./core/rules.ts";
export {
	JsonlDecodeError,
	type JsonlDecodeKind,
	type JsonlErrorPhase,
	JsonlSessionError,
	type JsonlSessionErrorCode,
	type JsonlWriteOutcome,
} from "./core/session/jsonl-errors.ts";
export { SessionAlreadyExistsError } from "./core/session/stores/jsonl-session-store.ts";
export {
	type BranchSummaryEntry,
	buildSessionContext,
	type CompactionEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	InMemorySessionManager,
	LocalSessionManager,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	RemoteSessionClient,
	RemoteSessionClientError,
	type RemoteSessionClientOptions,
	RemoteSessionManager,
	type RemoteSessionOperation,
	RemoteSessionProtocolError,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	type SessionManager,
	type SessionMessageEntry,
	type SessionTreeNode,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.ts";
export {
	type CompactionSettings,
	type FullscreenExitOutput,
	type ImageSettings,
	type MarkdownSettings,
	type MermaidRenderingMode,
	type PackageSource,
	type RetrySettings,
	SettingsManager,
	type ToolSettings,
} from "./core/settings-manager.ts";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsOptions,
	type LoadSkillsResult,
	type LoadSkillsWithOperationsOptions,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
	SkillLoader,
} from "./core/skills.ts";
export { createSyntheticSourceInfo } from "./core/source-info.ts";
// Tools
export {
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	createBashTool,
	createBashToolDefinition,
	createCodingTools,
	createEditTool,
	createEditToolDefinition,
	createFindTool,
	createFindToolDefinition,
	createGrepTool,
	createGrepToolDefinition,
	createLocalBashOperations,
	createLsTool,
	createLsToolDefinition,
	createReadOnlyTools,
	createReadTool,
	createReadToolDefinition,
	createRemoteToolOperations,
	createSshToolOperations,
	createSubagentTool,
	createSubagentToolDefinition,
	createWebsearchTool,
	createWebsearchToolDefinition,
	createWriteTool,
	createWriteToolDefinition,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	DeferredRemoteToolOperations,
	type DeferredRemoteToolOperationsConfigureSshOptions,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	formatSize,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	LocalToolOperations,
	type LocalToolOperationsOptions,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	type ParsedSshTarget,
	parseBraveSearchResponse,
	parseDuckDuckGoResponse,
	parseFirecrawlSearchResponse,
	parseWebsearchToolOptions,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	RemoteToolOperations,
	SshToolOperations,
	type SshToolOperationsOptions,
	type SubagentDetails,
	type SubagentResult,
	type SubagentRunInfo,
	type SubagentRunner,
	type SubagentRunOutcome,
	type SubagentRunRegistry,
	type SubagentRunRequest,
	type SubagentRunsToolInput,
	type SubagentStatus,
	type SubagentToolInput,
	type SubagentToolOptions,
	type SubagentUsageStats,
	type ToolAccessMode,
	type ToolBackendInfo,
	type ToolExecOptions,
	type ToolFileStat,
	type ToolGlobOptions,
	type ToolGrepMatch,
	type ToolGrepOptions,
	type ToolGrepResult,
	type ToolOperations,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WebsearchProvider,
	type WebsearchResultItem,
	type WebsearchToolDetails,
	type WebsearchToolInput,
	type WebsearchToolOptions,
	WORKSPACE_TOOL_NAMES,
	type WorkspaceToolCatalogEntry,
	type WorkspaceToolDefinition,
	WorkspaceToolHost,
	type WorkspaceToolHostOptions,
	type WorkspaceToolInvocation,
	type WorkspaceToolName,
	type WorkspaceToolOptions,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
} from "./core/tools/index.ts";
export type { WorkspaceIdentity } from "./core/workspace-identity.ts";
// Main entry point
export { type MainOptions, main } from "./main.ts";
// Run modes for programmatic SDK usage
export {
	InteractiveMode,
	type InteractiveModeOptions,
	type JsonAgentSessionEvent,
	type ModelInfo,
	type PrintModeOptions,
	RpcClient,
	type RpcClientListSessionsResponse,
	type RpcClientOptions,
	type RpcCommand,
	type RpcEventListener,
	type RpcInstructionDefinition,
	type RpcListSessionsOptions,
	type RpcListSessionsResponse,
	type RpcResponse,
	type RpcSessionState,
	type RpcToolCallRequest,
	type RpcToolDefinition,
	type RpcToolHandler,
	runPrintMode,
	runRpcMode,
} from "./modes/index.ts";
// UI components for extensions
export {
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./modes/interactive/theme/theme.ts";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.ts";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.ts";
// Shell utilities
export { getShellConfig } from "./utils/shell.ts";
