/**
 * Core modules shared between all run modes.
 */

export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type PromptOptions,
	type SessionStats,
} from "./agent-session.ts";
export { type BashExecutorOptions, type BashResult, executeBashWithOperations } from "./bash-executor.ts";
export type { CompactionResult } from "./compaction/index.ts";
export { createEventBus, type EventBus, type EventBusController } from "./event-bus.ts";
// Extensions system
export {
	type AgentEndEvent,
	type AgentStartEvent,
	type AgentToolResult,
	type AgentToolUpdateCallback,
	type BeforeAgentStartEvent,
	type BeforeAgentStartEventResult,
	type BuildSystemPromptOptions,
	type ContextEvent,
	defineTool,
	discoverAndLoadExtensions,
	type ExecOptions,
	type ExecResult,
	type Extension,
	type ExtensionAPI,
	type ExtensionCommandContext,
	type ExtensionContext,
	type ExtensionError,
	type ExtensionEvent,
	type ExtensionFactory,
	type ExtensionFlag,
	type ExtensionHandler,
	ExtensionRunner,
	type ExtensionShortcut,
	type ExtensionUIContext,
	type LoadExtensionsResult,
	type MessageRenderer,
	type RegisteredCommand,
	type SessionBeforeCompactEvent,
	type SessionBeforeForkEvent,
	type SessionBeforeSwitchEvent,
	type SessionBeforeTreeEvent,
	type SessionCompactEvent,
	type SessionShutdownEvent,
	type SessionStartEvent,
	type SessionTreeEvent,
	type ToolCallEvent,
	type ToolCallEventResult,
	type ToolDefinition,
	type ToolRenderResultOptions,
	type ToolResultEvent,
	type TurnEndEvent,
	type TurnStartEvent,
	type WorkingIndicatorOptions,
} from "./extensions/index.ts";
export {
	createLspCodeActionsTool,
	createLspDefinitionTool,
	createLspDiagnosticsTool,
	createLspHoverTool,
	createLspReferencesTool,
	createLspRenameTool,
	createLspRuntimeState,
	formatAutoDiagnosticsForChangedFile,
	getLspLanguageId,
	LSP_LANGUAGE_BY_EXTENSION,
	LspClient,
	type LspClientOptions,
	type LspClientStartResult,
	type LspCodeActionsDetails,
	type LspDiagnosticsDetails,
	LspFileSync,
	type LspHoverDetails,
	type LspLifecycleOptions,
	type LspLocationDetails,
	LspManager,
	type LspManagerOptions,
	type LspRenameDetails,
	type LspRuntimeState,
	type LspServerConfig,
	type LspServerStatus,
	type LspTrackedDocument,
	registerLspLifecycleHandlers,
} from "./lsp/index.ts";
export {
	type CreatePiAgentOptions,
	PiAgent,
	type PiAgentDiagnostic,
	type PiAgentRuntimeHost,
	type PiAgentServices,
	type PiAgentSessionOptions,
	type ResolvePiAgentSessionOptionsContext,
	type ResolvePiAgentSessionOptionsResult,
} from "./pi-agent.ts";
export { createSyntheticSourceInfo } from "./source-info.ts";
